### ISSUE TITLE
Does not compile on FreeBSD 13.1

### ISSUE THREAD

**Issue by marklapointe** [Aquantia/aqtion-freebsd#26]
`# make
Warning: Object directory not changed from original /root/git/aqtion-freebsd
cc  -O2 -pipe -DIFLIB -ferror-limit=1  -fno-strict-aliasing -Werror -D_KERNEL -DKLD_MODULE -nostdinc  -I/usr/include -include /root/git/aqtion-freebsd/opt_global.h -I. -I/usr/src/sys -I/usr/src/sys/contrib/ck/include -fno-common  -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdebug-prefix-map=./machine=/usr/src/sys/amd64/include -fdebug-prefix-map=./x86=/usr/src/sys/x86/include     -MD  -MF.depend.aq_main.o -MTaq_main.o -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -msoft-float  -fno-asynchronous-unwind-tables -ffreestanding -fwrapv -fstack-protector -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error=tautological-compare -Wno-error=empty-body -Wno-error=parentheses-equality -Wno-error=unused-function -Wno-error=pointer-sign -Wno-error=shift-negative-value -Wno-address-of-packed-member -Wno-error=unused-but-set-variable -Wno-format-zero-length   -mno-aes -mno-avx  -std=iso9899:1999 -c aq_main.c -o aq_main.o
In file included from aq_main.c:43:
In file included from /usr/include/sys/bus.h:744:
./bus_if.h:1260:50: error: unknown type name 'device_property_type_t'
                                   size_t _size, device_property_type_t type);
                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
*** Error code 1

Stop.
`
